name: 기능 제안
description: 제품 또는 개발환경 개선을 제안해 주세요.
title: "[Feature] "
labels:
  - enhancement
body:
  - type: textarea
    id: problem
    attributes:
      label: 해결하려는 문제
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: 제안 내용
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: 고려한 대안
